import { Router } from "express";
import authRoutes from "./authRoutes.js";
import bookingDraftRoutes from "./bookingDraftRoutes.js";
import cabinRoutes from "./cabinRoutes.js";
import cruiseRoutes from "./cruiseRoutes.js";
import destinationRoutes from "./destinationRoutes.js";
import experienceRoutes from "./experienceRoutes.js";
import empleadoRoutes from "./empleadoRoutes.js";
import invoiceRoutes from "./invoiceRoutes.js";
import manageBookingRoutes from "./manageBookingRoutes.js";
import monedaRoutes from "./monedaRoutes.js";
import pagoAdminRoutes from "./pagoAdminRoutes.js";
import pasajeroRoutes from "./pasajeroRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import profileRoutes from "./profileRoutes.js";
import reporteRoutes from "./reporteRoutes.js";
import reservaRoutes from "./reservaRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
import voyageHistoryRoutes from "./voyageHistoryRoutes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/booking-drafts", bookingDraftRoutes);
router.use("/cabinas", cabinRoutes);
router.use("/cruceros", cruiseRoutes);
router.use("/destinations", destinationRoutes);
router.use("/experiences", experienceRoutes);
router.use("/empleados", empleadoRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/manage-booking", manageBookingRoutes);
router.use("/monedas", monedaRoutes);
router.use("/pagos", pagoAdminRoutes);
router.use("/pasajeros", pasajeroRoutes);
router.use("/payments", paymentRoutes);
router.use("/profile", profileRoutes);
router.use("/reportes", reporteRoutes);
router.use("/reservas", reservaRoutes);
router.use("/reviews", reviewRoutes);
router.use("/voyage-history", voyageHistoryRoutes);

export default router;
